// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package sqlcdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Annualreview struct {
	ID         int32
	Empid      int32
	Reviewdate pgtype.Date
}

type Employee struct {
	ID              int32
	Firstname       string
	Lastname        string
	Hiredate        pgtype.Date
	Terminationdate pgtype.Date
	Salary          pgtype.Numeric
}
